### ISSUE TITLE
No longer works with Scala 2.13.12

### ISSUE THREAD

**Issue by bursauxa** [bizzabo/play-json-extensions#93]
This is probably more a problem with the Scala compiler introducing a breaking change, but here's a heads-up that this library no longer works with Scala 2.13.12.

**Update 2024-11-13**

The Scala team considers this library an "outlaw" (more details in https://github.com/scala/bug/issues/12862).

A compliant fork has been publisher by @rtyley and can be found at https://github.com/guardian/play-json-extensions.

**Comment by dejvid** [comment]
Yes it crashes with strange error when switching to scala 2.13.12 but switching back to 2.13.11 works. 
`
scala: ## Exception when compiling 934 sources to /Users/technobug/razvoj/BA-Core/target/scala-2.13/classes
java.lang.NoSuchMethodError: 'void scala.tools.nsc.ast.Trees$TypeTreeWithDeferredRefCheck.<init>(scala.tools.nsc.Global, scala.Function0)'
ai.x.play.json.Macros.verifyKnownDirectSubclassesPostTyper(play-json.scala:353)
ai.x.play.json.Macros.formatSealedInternal(play-json.scala:444)
ai.x.play.json.Macros.formatSealed(play-json.scala:396)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers.$anonfun$resolveJavaReflectionRuntime$5(JavaReflectionRuntimes.scala:45)
scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime(Macros.scala:796)
scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime$(Macros.scala:772)
scala.tools.nsc.Global$$anon$6.macroExpandWithRuntime(Global.scala:511)
scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$2(Macros.scala:601)
scala.tools.nsc.Global.withInfoLevel(Global.scala:254)
scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:594)
scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:556)
scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:757)
scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:755)
scala.tools.nsc.Global$$anon$6.standardMacroExpand(Global.scala:511)
scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$11.default(AnalyzerPlugins.scala:474)
scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$11.default(AnalyzerPlugins.scala:471)
scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:428)
scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:471)
scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:471)
scala.tools.nsc.Global$$anon$6.pluginsMacroExpand(Global.scala:511)
scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:746)
scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:739)
scala.tools.nsc.Global$$anon$6.macroExpand(Global.scala:511)
scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1236)
scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1307)
scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1280)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6168)
scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:6242)
scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1137)
scala.tools.nsc.typechecker.Namers$Namer.inferredValTpt$1(Namers.scala:1775)
scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1788)
scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1976)
scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1926)
scala.tools.nsc.typechecker.Namers$Namer$ValTypeCompleter.completeImpl(Namers.scala:944)
scala.tools.nsc.typechecker.Namers$Namer$AccessorTypeCompleter.completeImpl(Namers.scala:968)
scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2123)
scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2121)
scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2116)
scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1565)
scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1537)
scala.reflect.internal.Symbols$Symbol.tpeHK(Symbols.scala:1491)
scala.reflect.internal.Types$Type.computeMemberType(Types.scala:724)
scala.reflect.internal.Symbols$MethodSymbol.typeAsMemberOf(Symbols.scala:3081)
scala.reflect.internal.Types$Type.memberType(Types.scala:719)
scala.tools.nsc.typechecker.Implicits$ImplicitInfo.tpe(Implicits.scala:235)
scala.tools.nsc.typechecker.Implicits$ImplicitInfo.computeErroneous(Implicits.scala:270)
scala.tools.nsc.typechecker.Implicits$ImplicitInfo.isCyclicOrErroneous(Implicits.scala:265)
scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.isIneligible(Implicits.scala:1034)
scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.survives(Implicits.scala:1043)
scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.eligibleNew(Implicits.scala:1123)
scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.<init>(Implicits.scala:1177)
scala.tools.nsc.typechecker.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1305)
scala.tools.nsc.typechecker.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1699)
scala.tools.nsc.typechecker.Implicits.inferImplicit1(Implicits.scala:112)
scala.tools.nsc.typechecker.Implicits.inferImplicit(Implicits.scala:91)
scala.tools.nsc.typechecker.Implicits.inferImplicit$(Implicits.scala:88)
scala.tools.nsc.Global$$anon$6.inferImplicit(Global.scala:511)
scala.tools.nsc.typechecker.Implicits.inferImplicitFor(Implicits.scala:46)
scala.tools.nsc.typechecker.Implicits.inferImplicitFor$(Implicits.scala:45)
scala.tools.nsc.Global$$anon$6.inferImplicitFor(Global.scala:511)
scala.tools.nsc.typechecker.Typers$Typer.applyImplicitArgs(Typers.scala:263)
scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$1(Typers.scala:868)
scala.tools.nsc.typechecker.Typers$Typer.adaptToImplicitMethod$1(Typers.scala:488)
scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1303)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6168)
scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:6251)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:6098)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5160)
scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5162)
scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5194)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:6097)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:6242)
scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1137)
scala.tools.nsc.typechecker.Namers$Namer.inferredValTpt$1(Namers.scala:1775)
scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1788)
scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1976)
scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1926)
scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:874)
scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2123)
scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2121)
scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2116)
scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1565)
scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1537)
scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1726)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5734)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6231)
scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3470)
scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3470)
scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2597)
scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:6071)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:6107)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:6242)
scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1137)
scala.tools.nsc.typechecker.Namers$Namer.methodSig(Namers.scala:1492)
scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1975)
scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1926)
scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:874)
scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2123)
scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2121)
scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2116)
scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1565)
scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1537)
scala.reflect.internal.Symbols$Symbol.cookJavaRawInfo(Symbols.scala:1753)
scala.tools.nsc.typechecker.Infer$Inferencer.checkAccessible(Infer.scala:302)
scala.tools.nsc.typechecker.Typers$Typer.makeAccessible(Typers.scala:577)
scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$63(Typers.scala:5443)
scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:712)
scala.tools.nsc.typechecker.Typers$Typer.typedSelect$1(Typers.scala:5443)
scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:5513)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:6098)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5160)
scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5162)
scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5194)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:6097)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.typedCase(Typers.scala:6242)
scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedCases$1(Typers.scala:2657)
scala.tools.nsc.typechecker.Typers$Typer.typedCases(Typers.scala:2656)
scala.tools.nsc.typechecker.Typers$Typer.typedMatch(Typers.scala:2668)
scala.tools.nsc.typechecker.Typers$Typer.typedVirtualizedMatch$1(Typers.scala:4851)
scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:6076)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:6107)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.typedTry$1(Typers.scala:6242)
scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:6083)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:6107)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.doTypedFunction(Typers.scala:6242)
scala.tools.nsc.typechecker.Typers$Typer.typedFunction(Typers.scala:3139)
scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$108(Typers.scala:6035)
scala.tools.nsc.typechecker.Typers$Typer.typedFunction$1(Typers.scala:497)
scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:6075)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:6107)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:3488)
scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3892)
scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3911)
scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5183)
scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5194)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:6097)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.typedIf$1(Typers.scala:6242)
scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:6073)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:6107)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6231)
scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3470)
scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3470)
scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2597)
scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:6071)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:6107)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.typedIf$1(Typers.scala:6242)
scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:6073)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:6107)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:6242)
scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1137)
scala.tools.nsc.typechecker.Namers$Namer.inferredValTpt$1(Namers.scala:1775)
scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1788)
scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1976)
scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1926)
scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:874)
scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2123)
scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2121)
scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2116)
scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1565)
scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1537)
scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1726)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5734)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6231)
scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3470)
scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3470)
scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2597)
scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:6071)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:6107)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.typedCase(Typers.scala:6242)
scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedCases$1(Typers.scala:2657)
scala.tools.nsc.typechecker.Typers$Typer.typedCases(Typers.scala:2656)
scala.tools.nsc.typechecker.Typers$Typer.typedMatch(Typers.scala:2668)
scala.tools.nsc.typechecker.Typers$Typer.typedVirtualizedMatch$1(Typers.scala:4851)
scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:6076)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:6107)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:6242)
scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1137)
scala.tools.nsc.typechecker.Namers$Namer.inferredValTpt$1(Namers.scala:1775)
scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1788)
scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1976)
scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1926)
scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:874)
scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2123)
scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2121)
scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2116)
scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1565)
scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1537)
scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1726)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5734)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6231)
scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3470)
scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3470)
scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2597)
scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:6071)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:6107)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.doTypedFunction(Typers.scala:6242)
scala.tools.nsc.typechecker.Typers$Typer.typedFunction(Typers.scala:3139)
scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$108(Typers.scala:6035)
scala.tools.nsc.typechecker.Typers$Typer.typedFunction$1(Typers.scala:497)
scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:6075)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:6107)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:3488)
scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgWithFormal$1(PatternTypers.scala:136)
scala.tools.nsc.typechecker.PatternTypers$PatternTyper.$anonfun$typedArgsForFormals$4(PatternTypers.scala:150)
scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgsForFormals(PatternTypers.scala:150)
scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgsForFormals$(PatternTypers.scala:131)
scala.tools.nsc.typechecker.Typers$Typer.typedArgsForFormals(Typers.scala:203)
scala.tools.nsc.typechecker.Typers$Typer.handleMonomorphicCall$1(Typers.scala:3823)
scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3874)
scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$28(Typers.scala:5093)
scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
scala.tools.nsc.typechecker.Typers$Typer.tryTypedApply$1(Typers.scala:5093)
scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5181)
scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5194)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:6097)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:6242)
scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1137)
scala.tools.nsc.typechecker.Namers$Namer.methodSig(Namers.scala:1492)
scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1975)
scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1926)
scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:874)
scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2123)
scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2121)
scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2116)
scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1565)
scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1537)
scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1726)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5734)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6231)
scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3470)
scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3470)
scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2089)
scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1927)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:6060)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6231)
scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3470)
scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3470)
scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5743)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:6063)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6153)
scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:124)
scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:480)
scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:111)
scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1546)
scala.tools.nsc.Global$Run.compileUnits(Global.scala:1530)
scala.tools.nsc.Global$Run.compileSources(Global.scala:1522)
scala.tools.nsc.Global$Run.compileFiles(Global.scala:1635)
xsbt.CachedCompiler0.run(CompilerBridge.scala:163)
xsbt.CachedCompiler0.run(CompilerBridge.scala:134)
xsbt.CompilerBridge.run(CompilerBridge.scala:39)
sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:193)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:183)
sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:179)
sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:177)
sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:463)
sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:418)
sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:505)
sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:405)
sbt.internal.inc.Incremental$.apply(Incremental.scala:171)
sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
org.jetbrains.jps.incremental.scala.local.SbtCompiler.$anonfun$doCompile$4(SbtCompiler.scala:93)
scala.util.Try$.apply(Try.scala:210)
org.jetbrains.jps.incremental.scala.local.SbtCompiler.doCompile(SbtCompiler.scala:91)
org.jetbrains.jps.incremental.scala.local.SbtCompiler.compile(SbtCompiler.scala:21)
org.jetbrains.jps.incremental.scala.local.LocalServer.doCompile(LocalServer.scala:47)
org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:25)
org.jetbrains.jps.incremental.scala.remote.Main$.compileLogic(Main.scala:208)
org.jetbrains.jps.incremental.scala.remote.Main$.$anonfun$handleCommand$1(Main.scala:193)
org.jetbrains.jps.incremental.scala.remote.Main$.decorated$1(Main.scala:180)
org.jetbrains.jps.incremental.scala.remote.Main$.handleCommand(Main.scala:190)
org.jetbrains.jps.incremental.scala.remote.Main$.serverLogic(Main.scala:163)
org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:103)
org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
`

**Comment by dejvid** [comment]
What is workaround for this?

**Comment by gaeljw** [comment]
For anyone coming here, just letting you know that a [fork](https://github.com/guardian/play-json-extensions) has been created thanks to @rtyley. See https://github.com/scala/bug/issues/12862#issuecomment-2459871876

> I've released [an updated artifact](https://index.scala-lang.org/guardian/play-json-extensions/artifacts/play-json-extensions/1.0.2) against Scala 2.13:
>
> `"com.gu" %% "play-json-extensions" % "1.0.2"`
